<?= $this->extend($layout ?? 'layouts/main_user') ?>
<?= $this->section('content') ?>

<div class="container-fluid">
    <?php if (session()->getFlashdata('error')): ?><div class="alert alert-danger border-0 shadow-sm"><?= esc(session()->getFlashdata('error')) ?></div><?php endif; ?>

    <div class="slams-page-header">
        <div class="slams-page-header-left">
            <h1 class="slams-page-title">Email Preview</h1>
            <p class="slams-page-subtitle">This is the email content generated by the system.</p>
        </div>
        <div class="slams-page-header-actions">
            <a href="/dashboard/emails" class="btn btn-glass btn-sm">Back to Inbox</a>
            <a href="/dashboard/notifications" class="btn btn-glass btn-sm">Notifications</a>
        </div>
    </div>

    <div class="glass-card mb-4">
        <div class="card-body">
            <div class="d-flex flex-column flex-md-row justify-content-between gap-3">
                <div>
                    <div class="text-muted small">Subject</div>
                    <div class="fw-semibold"><?= esc($email['subject'] ?? 'Email') ?></div>
                </div>
                <div>
                    <div class="text-muted small">To</div>
                    <div class="fw-semibold"><?= esc($email['to_email'] ?? '-') ?></div>
                </div>
                <div>
                    <div class="text-muted small">Generated</div>
                    <div class="fw-semibold"><?= esc(! empty($email['created_at']) ? date('d-m-Y H:i', strtotime($email['created_at'])) : '-') ?></div>
                </div>
            </div>
            <?php if (! empty($email['has_attachment'])): ?>
                <div class="mt-3">
                    <span class="badge rounded-pill bg-light text-dark border">Attachment</span>
                    <span class="small text-muted ms-2"><?= esc($email['attachment_name'] ?? 'calendar.ics') ?></span>
                </div>
            <?php endif; ?>
        </div>
    </div>

    <div class="glass-card">
        <div class="card-body">
            <div class="email-preview">
                <?= $email['body'] ?? '' ?>
            </div>
        </div>
    </div>
</div>

<?= $this->endSection() ?>
